debug = true
ignore_suffixes = ["looptest.dnstapir.se", "org"]
include_invalid_etlds = true

[nats]
debug = true
url = "nats://nats:4222"
event_subject = "core-integration-test.events.new_qname"
observation_subject_prefix = "core-integration-test.observations"
private_subject_prefix = "core-integration-test.scratchpad"
seen_domains_subject_prefix = "core-integration-test.internal.seen-domains"

[[nats.observation_buckets]]
observation = "globally_new"
name = "globally_new"
create = false
ttl = 10

[nats.seen_domains_bucket]
name = "seen_domains"
create = true

[api]
active = false
