debug = true
interval = 0
looptest_match_suffix = "from-edge.looptest.dnstapir.se."

[nats]
debug = true
url = "nats://nats:4222"
event_subject = "core-integration-test.events.new_qname"
observation_subject_prefix = "core-integration-test.observations"

[[nats.observation_buckets]]
name = "looptest"
observation = "looptest"
ttl = 10
create = false

[api]
active = false
